import { Edu_NSW_ACT_Foundation, Fira_Sans_Condensed } from "next/font/google";
import "./globals.css";
import Footer from "./_components/Footer";

const herofont = Edu_NSW_ACT_Foundation({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-herofont",
});
export const metadata = {
  title: "Eazweb",
  description: "Generated by create next app",
};

const inter = Fira_Sans_Condensed({
  subsets: ["latin"],
  weight: ["100", "300", "400"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="m-0">
          {children}

          <Footer />
        </div>
      </body>
    </html>
  );
}
