import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./_components/Footer";
import { motion, useInView, useAnimation } from "framer-motion";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Eazweb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
