import { Fira_Sans_Condensed, Inter } from "next/font/google";
import "./globals.css";
import Footer from "./_components/Footer";

const herofont = Fira_Sans_Condensed({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-herofont",
});
export const metadata = {
  title: "Eazweb",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="m-0">
          {children}

          <Footer />
        </div>
      </body>
    </html>
  );
}
